
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package main.java.com.comviva.flowone.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-05-07T09:57:43.546-03:00
 * Generated source version: 3.3.4
 *
 */

@javax.jws.WebService(
                      serviceName = "InstantLinkWebServices",
                      portName = "InstantLinkWebServicesPort",
                      targetNamespace = "http://soa.comptel.com/2011/02/instantlink",
                      wsdlLocation = "file:/C:/Users/tbel/Documents/workspace_new/ASA_FlowOne_Client/WebContent/InstantLinkWebServices.wsdl",
                      endpointInterface = "main.java.com.comviva.flowone.client.InstantLinkSOA")

public class InstantLinkWebServicesPortImpl implements InstantLinkSOA {

    private static final Logger LOG = Logger.getLogger(InstantLinkWebServicesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see main.java.com.comviva.flowone.client.InstantLinkSOA#delete(main.java.com.comviva.flowone.client.DeleteRequest deleteRequest)*
     */
    public main.java.com.comviva.flowone.client.Response delete(DeleteRequest deleteRequest) {
        LOG.info("Executing operation delete");
        System.out.println(deleteRequest);
        try {
            main.java.com.comviva.flowone.client.Response _return = new main.java.com.comviva.flowone.client.Response();
            main.java.com.comviva.flowone.client.ResponseHeader _returnResponseHeader = new main.java.com.comviva.flowone.client.ResponseHeader();
            _returnResponseHeader.setRequestId(-1981200637129332557l);
            _returnResponseHeader.setStatus(1928957439);
            _returnResponseHeader.setOrderNo("OrderNo342693997");
            _returnResponseHeader.setStatusMessage("StatusMessage-159508308");
            _returnResponseHeader.setStatusMessageId("StatusMessageId1761732479");
            _returnResponseHeader.setPriority(Integer.valueOf(-338239355));
            _returnResponseHeader.setReqUser("ReqUser-727321495");
            _returnResponseHeader.setReceivedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.600-03:00"));
            _returnResponseHeader.setFinishedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.602-03:00"));
            _return.setResponseHeader(_returnResponseHeader);
            main.java.com.comviva.flowone.client.Response.ResponseParameters _returnResponseParameters = new main.java.com.comviva.flowone.client.Response.ResponseParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnResponseParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnResponseParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnResponseParametersParameterVal1.setName("Name-1708777957");
            _returnResponseParametersParameterVal1.setValue("Value-2013234902");
            _returnResponseParametersParameterVal1.setTags("Tags1668424884");
            _returnResponseParametersParameterVal1.setOrderParam(Boolean.valueOf(false));
            _returnResponseParametersParameter.add(_returnResponseParametersParameterVal1);
            _returnResponseParameters.getParameter().addAll(_returnResponseParametersParameter);
            _return.setResponseParameters(_returnResponseParameters);
            main.java.com.comviva.flowone.client.Response.RequestParameters _returnRequestParameters = new main.java.com.comviva.flowone.client.Response.RequestParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnRequestParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnRequestParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnRequestParametersParameterVal1.setName("Name-440354854");
            _returnRequestParametersParameterVal1.setValue("Value74952017");
            _returnRequestParametersParameterVal1.setTags("Tags954266520");
            _returnRequestParametersParameterVal1.setOrderParam(Boolean.valueOf(false));
            _returnRequestParametersParameter.add(_returnRequestParametersParameterVal1);
            _returnRequestParameters.getParameter().addAll(_returnRequestParametersParameter);
            _return.setRequestParameters(_returnRequestParameters);
            main.java.com.comviva.flowone.client.Response.Notifications _returnNotifications = new main.java.com.comviva.flowone.client.Response.Notifications();
            java.util.List<main.java.com.comviva.flowone.client.Notification> _returnNotificationsNotification = new java.util.ArrayList<main.java.com.comviva.flowone.client.Notification>();
            main.java.com.comviva.flowone.client.Notification _returnNotificationsNotificationVal1 = new main.java.com.comviva.flowone.client.Notification();
            _returnNotificationsNotificationVal1.setOrderNo("OrderNo-236346702");
            _returnNotificationsNotificationVal1.setRequestId(-4349144722654818152l);
            _returnNotificationsNotificationVal1.setLevel(-135024574);
            _returnNotificationsNotificationVal1.setTimeStamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.604-03:00"));
            _returnNotificationsNotificationVal1.setMessageId("MessageId-2522898");
            _returnNotificationsNotificationVal1.setMessage("Message1899128769");
            _returnNotificationsNotification.add(_returnNotificationsNotificationVal1);
            _returnNotifications.getNotification().addAll(_returnNotificationsNotification);
            _return.setNotifications(_returnNotifications);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see main.java.com.comviva.flowone.client.InstantLinkSOA#display(main.java.com.comviva.flowone.client.DisplayRequest displayRequest)*
     */
    public main.java.com.comviva.flowone.client.Response display(DisplayRequest displayRequest) {
        LOG.info("Executing operation display");
        System.out.println(displayRequest);
        try {
            main.java.com.comviva.flowone.client.Response _return = new main.java.com.comviva.flowone.client.Response();
            main.java.com.comviva.flowone.client.ResponseHeader _returnResponseHeader = new main.java.com.comviva.flowone.client.ResponseHeader();
            _returnResponseHeader.setRequestId(-6185257756114568056l);
            _returnResponseHeader.setStatus(-388282780);
            _returnResponseHeader.setOrderNo("OrderNo2129892380");
            _returnResponseHeader.setStatusMessage("StatusMessage1461992669");
            _returnResponseHeader.setStatusMessageId("StatusMessageId-402066958");
            _returnResponseHeader.setPriority(Integer.valueOf(-2065833802));
            _returnResponseHeader.setReqUser("ReqUser-993721921");
            _returnResponseHeader.setReceivedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.606-03:00"));
            _returnResponseHeader.setFinishedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.606-03:00"));
            _return.setResponseHeader(_returnResponseHeader);
            main.java.com.comviva.flowone.client.Response.ResponseParameters _returnResponseParameters = new main.java.com.comviva.flowone.client.Response.ResponseParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnResponseParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnResponseParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnResponseParametersParameterVal1.setName("Name-823761802");
            _returnResponseParametersParameterVal1.setValue("Value-1849855083");
            _returnResponseParametersParameterVal1.setTags("Tags255958997");
            _returnResponseParametersParameterVal1.setOrderParam(Boolean.valueOf(true));
            _returnResponseParametersParameter.add(_returnResponseParametersParameterVal1);
            _returnResponseParameters.getParameter().addAll(_returnResponseParametersParameter);
            _return.setResponseParameters(_returnResponseParameters);
            main.java.com.comviva.flowone.client.Response.RequestParameters _returnRequestParameters = new main.java.com.comviva.flowone.client.Response.RequestParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnRequestParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnRequestParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnRequestParametersParameterVal1.setName("Name2054274266");
            _returnRequestParametersParameterVal1.setValue("Value-35792828");
            _returnRequestParametersParameterVal1.setTags("Tags1693786822");
            _returnRequestParametersParameterVal1.setOrderParam(Boolean.valueOf(false));
            _returnRequestParametersParameter.add(_returnRequestParametersParameterVal1);
            _returnRequestParameters.getParameter().addAll(_returnRequestParametersParameter);
            _return.setRequestParameters(_returnRequestParameters);
            main.java.com.comviva.flowone.client.Response.Notifications _returnNotifications = new main.java.com.comviva.flowone.client.Response.Notifications();
            java.util.List<main.java.com.comviva.flowone.client.Notification> _returnNotificationsNotification = new java.util.ArrayList<main.java.com.comviva.flowone.client.Notification>();
            main.java.com.comviva.flowone.client.Notification _returnNotificationsNotificationVal1 = new main.java.com.comviva.flowone.client.Notification();
            _returnNotificationsNotificationVal1.setOrderNo("OrderNo2044016909");
            _returnNotificationsNotificationVal1.setRequestId(-1527106057607983960l);
            _returnNotificationsNotificationVal1.setLevel(-1422151957);
            _returnNotificationsNotificationVal1.setTimeStamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.608-03:00"));
            _returnNotificationsNotificationVal1.setMessageId("MessageId-1935201144");
            _returnNotificationsNotificationVal1.setMessage("Message-518912648");
            _returnNotificationsNotification.add(_returnNotificationsNotificationVal1);
            _returnNotifications.getNotification().addAll(_returnNotificationsNotification);
            _return.setNotifications(_returnNotifications);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see main.java.com.comviva.flowone.client.InstantLinkSOA#create(main.java.com.comviva.flowone.client.CreateRequest createRequest)*
     */
    public main.java.com.comviva.flowone.client.Response create(CreateRequest createRequest) {
        LOG.info("Executing operation create");
        System.out.println(createRequest);
        try {
            main.java.com.comviva.flowone.client.Response _return = new main.java.com.comviva.flowone.client.Response();
            main.java.com.comviva.flowone.client.ResponseHeader _returnResponseHeader = new main.java.com.comviva.flowone.client.ResponseHeader();
            _returnResponseHeader.setRequestId(5351408807075803630l);
            _returnResponseHeader.setStatus(-1230456807);
            _returnResponseHeader.setOrderNo("OrderNo987899848");
            _returnResponseHeader.setStatusMessage("StatusMessage-520368632");
            _returnResponseHeader.setStatusMessageId("StatusMessageId-1602528037");
            _returnResponseHeader.setPriority(Integer.valueOf(-2026331897));
            _returnResponseHeader.setReqUser("ReqUser1251018786");
            _returnResponseHeader.setReceivedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.611-03:00"));
            _returnResponseHeader.setFinishedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.611-03:00"));
            _return.setResponseHeader(_returnResponseHeader);
            main.java.com.comviva.flowone.client.Response.ResponseParameters _returnResponseParameters = new main.java.com.comviva.flowone.client.Response.ResponseParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnResponseParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnResponseParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnResponseParametersParameterVal1.setName("Name671506654");
            _returnResponseParametersParameterVal1.setValue("Value-869494973");
            _returnResponseParametersParameterVal1.setTags("Tags737801848");
            _returnResponseParametersParameterVal1.setOrderParam(Boolean.valueOf(false));
            _returnResponseParametersParameter.add(_returnResponseParametersParameterVal1);
            _returnResponseParameters.getParameter().addAll(_returnResponseParametersParameter);
            _return.setResponseParameters(_returnResponseParameters);
            main.java.com.comviva.flowone.client.Response.RequestParameters _returnRequestParameters = new main.java.com.comviva.flowone.client.Response.RequestParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnRequestParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnRequestParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnRequestParametersParameterVal1.setName("Name1653732640");
            _returnRequestParametersParameterVal1.setValue("Value-269415459");
            _returnRequestParametersParameterVal1.setTags("Tags1853171991");
            _returnRequestParametersParameterVal1.setOrderParam(Boolean.valueOf(true));
            _returnRequestParametersParameter.add(_returnRequestParametersParameterVal1);
            _returnRequestParameters.getParameter().addAll(_returnRequestParametersParameter);
            _return.setRequestParameters(_returnRequestParameters);
            main.java.com.comviva.flowone.client.Response.Notifications _returnNotifications = new main.java.com.comviva.flowone.client.Response.Notifications();
            java.util.List<main.java.com.comviva.flowone.client.Notification> _returnNotificationsNotification = new java.util.ArrayList<main.java.com.comviva.flowone.client.Notification>();
            main.java.com.comviva.flowone.client.Notification _returnNotificationsNotificationVal1 = new main.java.com.comviva.flowone.client.Notification();
            _returnNotificationsNotificationVal1.setOrderNo("OrderNo-527903136");
            _returnNotificationsNotificationVal1.setRequestId(5128473464168020209l);
            _returnNotificationsNotificationVal1.setLevel(-1691370198);
            _returnNotificationsNotificationVal1.setTimeStamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.612-03:00"));
            _returnNotificationsNotificationVal1.setMessageId("MessageId-1066311773");
            _returnNotificationsNotificationVal1.setMessage("Message244122395");
            _returnNotificationsNotification.add(_returnNotificationsNotificationVal1);
            _returnNotifications.getNotification().addAll(_returnNotificationsNotification);
            _return.setNotifications(_returnNotifications);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see main.java.com.comviva.flowone.client.InstantLinkSOA#modify(main.java.com.comviva.flowone.client.ModifyRequest modifyRequest)*
     */
    public main.java.com.comviva.flowone.client.Response modify(ModifyRequest modifyRequest) {
        LOG.info("Executing operation modify");
        System.out.println(modifyRequest);
        try {
            main.java.com.comviva.flowone.client.Response _return = new main.java.com.comviva.flowone.client.Response();
            main.java.com.comviva.flowone.client.ResponseHeader _returnResponseHeader = new main.java.com.comviva.flowone.client.ResponseHeader();
            _returnResponseHeader.setRequestId(-7014675694594294584l);
            _returnResponseHeader.setStatus(1475648031);
            _returnResponseHeader.setOrderNo("OrderNo1286983086");
            _returnResponseHeader.setStatusMessage("StatusMessage1385352362");
            _returnResponseHeader.setStatusMessageId("StatusMessageId-1085493507");
            _returnResponseHeader.setPriority(Integer.valueOf(2137621573));
            _returnResponseHeader.setReqUser("ReqUser235210869");
            _returnResponseHeader.setReceivedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.615-03:00"));
            _returnResponseHeader.setFinishedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.615-03:00"));
            _return.setResponseHeader(_returnResponseHeader);
            main.java.com.comviva.flowone.client.Response.ResponseParameters _returnResponseParameters = new main.java.com.comviva.flowone.client.Response.ResponseParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnResponseParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnResponseParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnResponseParametersParameterVal1.setName("Name-1980464598");
            _returnResponseParametersParameterVal1.setValue("Value1766695951");
            _returnResponseParametersParameterVal1.setTags("Tags1444889857");
            _returnResponseParametersParameterVal1.setOrderParam(Boolean.valueOf(true));
            _returnResponseParametersParameter.add(_returnResponseParametersParameterVal1);
            _returnResponseParameters.getParameter().addAll(_returnResponseParametersParameter);
            _return.setResponseParameters(_returnResponseParameters);
            main.java.com.comviva.flowone.client.Response.RequestParameters _returnRequestParameters = new main.java.com.comviva.flowone.client.Response.RequestParameters();
            java.util.List<main.java.com.comviva.flowone.client.Parameter> _returnRequestParametersParameter = new java.util.ArrayList<main.java.com.comviva.flowone.client.Parameter>();
            main.java.com.comviva.flowone.client.Parameter _returnRequestParametersParameterVal1 = new main.java.com.comviva.flowone.client.Parameter();
            _returnRequestParametersParameterVal1.setName("Name1815195568");
            _returnRequestParametersParameterVal1.setValue("Value257486104");
            _returnRequestParametersParameterVal1.setTags("Tags1073794879");
            _returnRequestParametersParameterVal1.setOrderParam(Boolean.valueOf(true));
            _returnRequestParametersParameter.add(_returnRequestParametersParameterVal1);
            _returnRequestParameters.getParameter().addAll(_returnRequestParametersParameter);
            _return.setRequestParameters(_returnRequestParameters);
            main.java.com.comviva.flowone.client.Response.Notifications _returnNotifications = new main.java.com.comviva.flowone.client.Response.Notifications();
            java.util.List<main.java.com.comviva.flowone.client.Notification> _returnNotificationsNotification = new java.util.ArrayList<main.java.com.comviva.flowone.client.Notification>();
            main.java.com.comviva.flowone.client.Notification _returnNotificationsNotificationVal1 = new main.java.com.comviva.flowone.client.Notification();
            _returnNotificationsNotificationVal1.setOrderNo("OrderNo128365925");
            _returnNotificationsNotificationVal1.setRequestId(-5531959238088148559l);
            _returnNotificationsNotificationVal1.setLevel(-2011887257);
            _returnNotificationsNotificationVal1.setTimeStamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-05-07T09:57:43.616-03:00"));
            _returnNotificationsNotificationVal1.setMessageId("MessageId-1038104205");
            _returnNotificationsNotificationVal1.setMessage("Message226623224");
            _returnNotificationsNotification.add(_returnNotificationsNotificationVal1);
            _returnNotifications.getNotification().addAll(_returnNotificationsNotification);
            _return.setNotifications(_returnNotifications);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see main.java.com.comviva.flowone.client.InstantLinkSOA#getInstantLinkAvailability()*
     */
    public main.java.com.comviva.flowone.client.InstantLinkAvailabilityInfo getInstantLinkAvailability() {
        LOG.info("Executing operation getInstantLinkAvailability");
        try {
            main.java.com.comviva.flowone.client.InstantLinkAvailabilityInfo _return = new main.java.com.comviva.flowone.client.InstantLinkAvailabilityInfo();
            _return.setInstantLinkInstance("InstantLinkInstance1340362447");
            main.java.com.comviva.flowone.client.AvailInfoStatus _returnRunningStatus = main.java.com.comviva.flowone.client.AvailInfoStatus.STOPPING;
            _return.setRunningStatus(_returnRunningStatus);
            _return.setUptime(554701017626691449l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
