package main.java.com.comviva.flowone.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This is a service to send requests to InstantLink
 *
 * This class was generated by Apache CXF 3.3.4
 * 2020-05-07T09:57:43.618-03:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://soa.comptel.com/2011/02/instantlink", name = "InstantLinkSOA")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InstantLinkSOA {

    /**
     * Operation to delete activated service(s) from the network
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "http://soa.comptel.com/2011/02/instantlink", partName = "response")
    public Response delete(

        @WebParam(partName = "deleteRequest", name = "DeleteRequest", targetNamespace = "http://soa.comptel.com/2011/02/instantlink")
        DeleteRequest deleteRequest
    );

    /**
     * Operation to fetch parameters from the network
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "http://soa.comptel.com/2011/02/instantlink", partName = "response")
    public Response display(

        @WebParam(partName = "displayRequest", name = "DisplayRequest", targetNamespace = "http://soa.comptel.com/2011/02/instantlink")
        DisplayRequest displayRequest
    );

    /**
     * Operation to create (activate) service(s) in the network
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "http://soa.comptel.com/2011/02/instantlink", partName = "response")
    public Response create(

        @WebParam(partName = "createRequest", name = "CreateRequest", targetNamespace = "http://soa.comptel.com/2011/02/instantlink")
        CreateRequest createRequest
    );

    /**
     * Operation to modify already activated service(s) in the network
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "http://soa.comptel.com/2011/02/instantlink", partName = "response")
    public Response modify(

        @WebParam(partName = "modifyRequest", name = "ModifyRequest", targetNamespace = "http://soa.comptel.com/2011/02/instantlink")
        ModifyRequest modifyRequest
    );

    /**
     * Operation to get the current InstantLink status information
     */
    @WebMethod
    @WebResult(name = "InstantLinkAvailabilityInfo", targetNamespace = "http://soa.comptel.com/2011/02/instantlink", partName = "getInstantLinkAvailabilityResponse")
    public InstantLinkAvailabilityInfo getInstantLinkAvailability()
;
}
